version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - nilerr
    - staticcheck
    - unused
    - sqlclosecheck
formatters:
  enable:
    - gofmt
    - goimports
